replicaCount: 3

image:
  repository: kube-ai-guardian
  tag: "0.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 18080
  targetPort: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
