apiVersion: v1
kind: Service
metadata:
  name: guardian-api
  namespace: kube-ai-guardian

spec:
  selector:
    app: guardian-api

  ports:
    - protocol: TCP
      port: 18080
      targetPort: 8000

  type: ClusterIP
