apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardian-api
  namespace: kube-ai-guardian

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: guardian-api

  template:
    metadata:
      labels:
        app: guardian-api

    spec:
      containers:
        - name: guardian-api

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}


          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              drop:
                - ALL


          ports:
            - containerPort: {{ .Values.service.targetPort }}

          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
