apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged-containers
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: privileged-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - kube-ai-guardian
      validate:
        message: "Tryb privileged jest zabroniony."
        pattern:
          spec:
            containers:
              - =(securityContext):
                  =(privileged): "false"
